### ISSUE TITLE
Did this ever happen?

### ISSUE THREAD

**Issue by benschac** [mbStavola/4GP-Website#1]
@mbStavola @kevinmost

**Comment by benschac** [comment]
Yeah, issue #1! wooooooo

**Comment by mbStavola** [comment]
Out of the scope of our project!

(How're you doing by the way?)

**Comment by benschac** [comment]
Good, how've you been? Are you guys still doing hack-a-thons?

On Mon, Oct 26, 2015 at 10:15 PM, mbStavola notifications@github.com
wrote:

> Out of the scope of our project!
> 
> (How're you doing by the way?)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mbStavola/4GP-Website/issues/1#issuecomment-151344673
> .

## 

*Benjamin Schachter *• Project Manager
- http://www.dramafever.com/\*    |   bschachter@dramafever.com

**Comment by mbStavola** [comment]
Fine. We did Angelhack in the summer, didn't really get anywhere with that unfortunately. Really just been working for the most part. What about you? What have you been up to?

**Comment by benschac** [comment]
Working and stuff.  We should do another one of these hack-a-thons.  Win
more than $40 bucks. :)

On Tue, Oct 27, 2015 at 10:52 AM, mbStavola notifications@github.com
wrote:

> Fine. We did Angelhack in the summer, didn't really get anywhere with that
> unfortunately. Really just been working for the most part. What about you?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mbStavola/4GP-Website/issues/1#issuecomment-151528369
> .

## 

*Benjamin Schachter *• Project Manager
- http://www.dramafever.com/\*    |   bschachter@dramafever.com

**Comment by mbStavola** [comment]
I'd like to, what about you @kevinmost ?

**Comment by benschac** [comment]
Chief cookie officer.  Aka. CCO.

On Tue, Oct 27, 2015 at 2:23 PM, mbStavola notifications@github.com wrote:

> I'd like to, what about you @kevinmost https://github.com/kevinmost ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mbStavola/4GP-Website/issues/1#issuecomment-151599543
> .

## 

*Benjamin Schachter *• Project Manager
- http://www.dramafever.com/\*    |   bschachter@dramafever.com
